// Code generated by MockGen. DO NOT EDIT.
// Source: i_trading_service_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_trading_service_proxy.go -destination=mocks/mock_i_trading_service_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading-mcp/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockITradingServiceProxy is a mock of ITradingServiceProxy interface.
type MockITradingServiceProxy struct {
	ctrl     *gomock.Controller
	recorder *MockITradingServiceProxyMockRecorder
	isgomock struct{}
}

// MockITradingServiceProxyMockRecorder is the mock recorder for MockITradingServiceProxy.
type MockITradingServiceProxyMockRecorder struct {
	mock *MockITradingServiceProxy
}

// NewMockITradingServiceProxy creates a new mock instance.
func NewMockITradingServiceProxy(ctrl *gomock.Controller) *MockITradingServiceProxy {
	mock := &MockITradingServiceProxy{ctrl: ctrl}
	mock.recorder = &MockITradingServiceProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITradingServiceProxy) EXPECT() *MockITradingServiceProxyMockRecorder {
	return m.recorder
}

// InspectConnectorAuthorization mocks base method.
func (m *MockITradingServiceProxy) InspectConnectorAuthorization(ctx context.Context, accessToken string) (vo.ConnectorAuthorizationInspectionVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectConnectorAuthorization", ctx, accessToken)
	ret0, _ := ret[0].(vo.ConnectorAuthorizationInspectionVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectConnectorAuthorization indicates an expected call of InspectConnectorAuthorization.
func (mr *MockITradingServiceProxyMockRecorder) InspectConnectorAuthorization(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectConnectorAuthorization", reflect.TypeOf((*MockITradingServiceProxy)(nil).InspectConnectorAuthorization), ctx, accessToken)
}

// Send mocks base method.
func (m *MockITradingServiceProxy) Send(ctx context.Context, request vo.TradingServiceRequestVo, accessToken string) (vo.TradingServiceResponseVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, request, accessToken)
	ret0, _ := ret[0].(vo.TradingServiceResponseVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockITradingServiceProxyMockRecorder) Send(ctx, request, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockITradingServiceProxy)(nil).Send), ctx, request, accessToken)
}
