// Code generated by MockGen. DO NOT EDIT.
// Source: i_signed_in_session_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_signed_in_session_repository.go -destination=mocks/mock_i_signed_in_session_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domains "github.com/CodeMachine0121/go-trading-mcp/internal/domain/models/domains"
	vo "github.com/CodeMachine0121/go-trading-mcp/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockISignedInSessionRepository is a mock of ISignedInSessionRepository interface.
type MockISignedInSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISignedInSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockISignedInSessionRepositoryMockRecorder is the mock recorder for MockISignedInSessionRepository.
type MockISignedInSessionRepositoryMockRecorder struct {
	mock *MockISignedInSessionRepository
}

// NewMockISignedInSessionRepository creates a new mock instance.
func NewMockISignedInSessionRepository(ctrl *gomock.Controller) *MockISignedInSessionRepository {
	mock := &MockISignedInSessionRepository{ctrl: ctrl}
	mock.recorder = &MockISignedInSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISignedInSessionRepository) EXPECT() *MockISignedInSessionRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockISignedInSessionRepository) Find(sessionKey vo.SessionKeyVo) (domains.SignedInSessionDomain, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", sessionKey)
	ret0, _ := ret[0].(domains.SignedInSessionDomain)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockISignedInSessionRepositoryMockRecorder) Find(sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockISignedInSessionRepository)(nil).Find), sessionKey)
}

// Remove mocks base method.
func (m *MockISignedInSessionRepository) Remove(sessionKey vo.SessionKeyVo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", sessionKey)
}

// Remove indicates an expected call of Remove.
func (mr *MockISignedInSessionRepositoryMockRecorder) Remove(sessionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockISignedInSessionRepository)(nil).Remove), sessionKey)
}

// RemoveUnusable mocks base method.
func (m *MockISignedInSessionRepository) RemoveUnusable(isUnusable func(domains.SignedInSessionDomain) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveUnusable", isUnusable)
}

// RemoveUnusable indicates an expected call of RemoveUnusable.
func (mr *MockISignedInSessionRepositoryMockRecorder) RemoveUnusable(isUnusable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUnusable", reflect.TypeOf((*MockISignedInSessionRepository)(nil).RemoveUnusable), isUnusable)
}

// Save mocks base method.
func (m *MockISignedInSessionRepository) Save(sessionKey vo.SessionKeyVo, signedInSession domains.SignedInSessionDomain) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", sessionKey, signedInSession)
}

// Save indicates an expected call of Save.
func (mr *MockISignedInSessionRepositoryMockRecorder) Save(sessionKey, signedInSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockISignedInSessionRepository)(nil).Save), sessionKey, signedInSession)
}
