// Code generated by MockGen. DO NOT EDIT.
// Source: i_connector_authorization_verdict_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_connector_authorization_verdict_repository.go -destination=mocks/mock_i_connector_authorization_verdict_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domains "github.com/CodeMachine0121/go-trading-mcp/internal/domain/models/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockIConnectorAuthorizationVerdictRepository is a mock of IConnectorAuthorizationVerdictRepository interface.
type MockIConnectorAuthorizationVerdictRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIConnectorAuthorizationVerdictRepositoryMockRecorder
	isgomock struct{}
}

// MockIConnectorAuthorizationVerdictRepositoryMockRecorder is the mock recorder for MockIConnectorAuthorizationVerdictRepository.
type MockIConnectorAuthorizationVerdictRepositoryMockRecorder struct {
	mock *MockIConnectorAuthorizationVerdictRepository
}

// NewMockIConnectorAuthorizationVerdictRepository creates a new mock instance.
func NewMockIConnectorAuthorizationVerdictRepository(ctrl *gomock.Controller) *MockIConnectorAuthorizationVerdictRepository {
	mock := &MockIConnectorAuthorizationVerdictRepository{ctrl: ctrl}
	mock.recorder = &MockIConnectorAuthorizationVerdictRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConnectorAuthorizationVerdictRepository) EXPECT() *MockIConnectorAuthorizationVerdictRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockIConnectorAuthorizationVerdictRepository) Find(accessToken string, now time.Time) (domains.ConnectorAuthorizationDomain, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", accessToken, now)
	ret0, _ := ret[0].(domains.ConnectorAuthorizationDomain)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIConnectorAuthorizationVerdictRepositoryMockRecorder) Find(accessToken, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIConnectorAuthorizationVerdictRepository)(nil).Find), accessToken, now)
}

// Save mocks base method.
func (m *MockIConnectorAuthorizationVerdictRepository) Save(accessToken string, verdict domains.ConnectorAuthorizationDomain, now time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", accessToken, verdict, now)
}

// Save indicates an expected call of Save.
func (mr *MockIConnectorAuthorizationVerdictRepositoryMockRecorder) Save(accessToken, verdict, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIConnectorAuthorizationVerdictRepository)(nil).Save), accessToken, verdict, now)
}
